server:
  port: 9090
spring:
  security:
    user:
      name: moo
      password: moo123
  application:
    name: teacher-students
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/orclpdb
    driver:-class-name: oracle.jdbc.OracleDriver
    username: hr
    password: hr
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  messages:
    basename: messages
    encoding: UTF-8







